//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wc_REST
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NEREYEAPPEntities2 : DbContext
    {
        public NEREYEAPPEntities2()
            : base("name=wc_REST.Properties.Settings.conStr")
        {
        }
    
        //protected override void OnModelCreating(DbModelBuilder modelBuilder)
        //{
        //    throw new UnintentionalCodeFirstException();
        //}

        public virtual DbSet<tbl_comment> tbl_comment { get; set; }
        public virtual DbSet<tbl_error> tbl_error { get; set; }
        public virtual DbSet<tbl_score> tbl_score { get; set; }
        public virtual DbSet<tbl_user> tbl_user { get; set; }
        public virtual DbSet<tbl_wc> tbl_wc { get; set; }
        public virtual DbSet<tbl_wcfile> tbl_wcfile { get; set; }
        public virtual DbSet<tbl_request> tbl_request { get; set; }
    }
}
