//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wc_REST
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_request
    {
        public System.Guid Request_Id { get; set; }
        public double Request_wc_latitude { get; set; }
        public double Request_wc_longtitude { get; set; }
        public Nullable<bool> Request_wc_european { get; set; }
        public Nullable<bool> Request_wc_genderfemale { get; set; }
        public Nullable<bool> Request_wc_gendermale { get; set; }
        public Nullable<int> Request_wc_score { get; set; }
        public Nullable<bool> Request_wc_paper { get; set; }
        public Nullable<bool> Request_wc_ablution { get; set; }
        public Nullable<bool> Request_wc_music { get; set; }
        public Nullable<bool> Request_wc_babystop { get; set; }
        public Nullable<bool> Request_wc_fordisabled { get; set; }
        public Nullable<bool> Request_wc_approved { get; set; }
        public Nullable<bool> Request_wc_wifi { get; set; }
        public Nullable<bool> Request_wc_acpower { get; set; }
        public Nullable<bool> Request_wc_traditional { get; set; }
        public Nullable<bool> Request_wc_paid { get; set; }
        public System.DateTime Request_date { get; set; }
    }
}
