//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wc_REST
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_wcfile
    {
        public string wcfile_data { get; set; }
        public Nullable<System.DateTime> wcfile_date { get; set; }
        public System.Guid wcfile_id { get; set; }
        public System.Guid wcfile_wcid { get; set; }
        public System.Guid wcfile_userid { get; set; }
    
        public tbl_user tbl_user { get; set; }
        public tbl_wc tbl_wc { get; set; }
    }
}
