//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wc_REST
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_error
    {
        public int error_id { get; set; }
        public string error_data { get; set; }
        public string error_exception { get; set; }
    }
}
