//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wc_REST
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_wc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_wc()
        {
            this.tbl_comment = new HashSet<tbl_comment>();
            this.tbl_score = new HashSet<tbl_score>();
            this.tbl_wcfile = new HashSet<tbl_wcfile>();
        }
    
        public System.Guid wc_id { get; set; }
        public string wc_name { get; set; }
        public Nullable<double> wc_latitude { get; set; }
        public Nullable<double> wc_longtitude { get; set; }
        public Nullable<bool> wc_european { get; set; }
        public Nullable<bool> wc_genderfemale { get; set; }
        public Nullable<bool> wc_gendermale { get; set; }
        public Nullable<int> wc_score { get; set; }
        public Nullable<bool> wc_paper { get; set; }
        public Nullable<bool> wc_ablution { get; set; }
        public Nullable<bool> wc_music { get; set; }
        public Nullable<bool> wc_babystop { get; set; }
        public Nullable<bool> wc_fordisabled { get; set; }
        public Nullable<bool> wc_approved { get; set; }
        public Nullable<int> wc_notexistreport { get; set; }
        public string wc_type { get; set; }
        public Nullable<bool> wc_wifi { get; set; }
        public Nullable<bool> wc_acpower { get; set; }
        public Nullable<bool> wc_traditional { get; set; }
        public string wc_foreignid { get; set; }
        public Nullable<bool> wc_paid { get; set; }
        public int wc_inappropriatereport { get; set; }
        public Nullable<System.DateTime> wc_updateddate { get; set; }
        public System.DateTime wc_createddate { get; set; }
    //virtual kelimesi silindi.
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<tbl_comment> tbl_comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<tbl_score> tbl_score { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<tbl_wcfile> tbl_wcfile { get; set; }
    }
}
