//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wc_REST
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_user()
        {
            this.tbl_comment = new HashSet<tbl_comment>();
            this.tbl_score = new HashSet<tbl_score>();
            this.tbl_wcfile = new HashSet<tbl_wcfile>();
        }
    
        public string user_name { get; set; }
        public string user_surname { get; set; }
        public string user_mail { get; set; }
        public string user_deviceId { get; set; }
        public System.Guid user_id { get; set; }
        public string user_macAddress { get; set; }
        public string user_photourl { get; set; }
        public string user_token { get; set; }
        public bool user_banned { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<tbl_comment> tbl_comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<tbl_score> tbl_score { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<tbl_wcfile> tbl_wcfile { get; set; }
    }
}
